# Generated by Django 4.1.1 on 2022-09-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Roll_no', models.IntegerField(null=True)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField(null=True)),
                ('student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.student')),
            ],
        ),
    ]
