# Generated by Django 4.1.1 on 2022-09-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_alter_student_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='students',
            new_name='student',
        ),
    ]
