# Generated by Django 4.1.1 on 2022-09-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_rename_students_mark_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Date_of_Publish', models.DateField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.author')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.book')),
            ],
        ),
    ]
