# Generated by Django 4.1.1 on 2022-09-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_no', models.TextField(max_length=100)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationships.person')),
            ],
        ),
    ]
