# Generated by Django 4.1.1 on 2022-09-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0007_person_adhar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adhar',
            new_name='Aadhar',
        ),
    ]
