# Generated by Django 4.1.1 on 2022-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0008_rename_adhar_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Mobile',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
