# Generated by Django 4.1.1 on 2022-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0009_alter_person_email_alter_person_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='Marks',
            new_name='English',
        ),
        migrations.AddField(
            model_name='mark',
            name='Maths',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='Science',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='Social',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='Tamil',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='upload_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
