# Generated by Django 4.1.1 on 2022-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0010_rename_marks_mark_english_mark_maths_mark_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
