# Generated by Django 4.1.1 on 2022-09-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0011_alter_student_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar',
            old_name='Person',
            new_name='person',
        ),
    ]
