# Generated by Django 4.1.1 on 2022-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0012_rename_person_aadhar_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='modified_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='modified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
