# Generated by Django 4.1.1 on 2022-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0014_alter_mark_modified_on_alter_student_modified_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='modified_on',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='modified_on',
            new_name='modified_date',
        ),
        migrations.AddField(
            model_name='mark',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
