# Generated by Django 4.1.1 on 2022-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0017_rename_english_mark_mark_rename_maths_mark_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
