# Generated by Django 4.1.1 on 2022-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0021_alter_mark_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='modified_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
