# Generated by Django 4.1.1 on 2022-09-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Roll_no', models.IntegerField(max_length=30, null=True)),
                ('Address', models.TextField()),
            ],
        ),
    ]
